### ISSUE TITLE
Display highest warning in map

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#1]
Display highest warning level for flood and landslide in a map.

* County level
* Use warning for first of three days.
* See wiki for colors.

**Comment by raae** [comment]
Potential map base: https://cartodb.com/basemaps/

**Comment by raae** [comment]
Colors can be found in wiki: https://github.com/bGraphic/varsom-apps/wiki/Design-Profile.
Also, use the highest level for the next three days (not level for first of the three days).

**Comment by raae** [comment]
When colors and highest level logic is done, please invite @erjohnse to ionic view.

**Comment by kjellivar** [comment]
@raae Colors and highest level done, invited him now.
