### ISSUE TITLE
Menu hamburger should conform to platform behaviour

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#10]
On iOS is should be to the left and on android to the right. Should be done by Ionic.

**Comment by kjellivar** [comment]
Grunnen til at jeg ikke har helt llyst til å gjøre dette, er at man ikke kan swipe for å åpne menyen lengre, siden det ikke vil fungere sammen med "swipe to go back" på iOS.

**Comment by raae** [comment]
Den er grei. Og så rekker tommelen min letter opp til høyre side.
