### ISSUE TITLE
Better design for county flood/landslide preview

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#11]
Three day forecast for county to be used when selectin area in map on top of county view: #13
Should be easy for the user to figure out the days the forecast is fore.

**Comment by kjellivar** [comment]
Added wireframe to mybalsamiq project 
![uploads/3968bff6-2509-4e3a-a3a5-14b01ece1aa9/3 day forecast.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3968bff6-2509-4e3a-a3a5-14b01ece1aa9%2F3+day+forecast.png)

**Comment by kjellivar** [comment]
Alternativt
![uploads/ea03a4a7-d9b0-4aa6-8918-8c5b5ca00f51/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fea03a4a7-d9b0-4aa6-8918-8c5b5ca00f51%2Fblob)

**Comment by raae** [comment]
Alternativ 1 er nok best, men naturlig leserettning.

**Comment by raae** [comment]
Lurer på om det er bra om "overskrifen" skiller seg litt ut fra previewen. Og at kun området med selve previewen blir markert på touch og at pilen er sentrert på den "boksen". 

![uploads/bbe0713e-635d-421f-9cbc-cb4b3e9d9a59/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbbe0713e-635d-421f-9cbc-cb4b3e9d9a59%2Fimage.png)

**Comment by erjohnse** [comment]
👌🏼

Den torsdag 8. oktober 2015 skrev Benedicte Raae <notifications@github.com>
følgende:

**Comment by raae** [comment]
Det blir litt for stort og på min mini iPhone er det ikke plass til jordskred/flom teksten. 
Gjør firkantene til ca 70% av størrelsen det er nå?

**Comment by kjellivar** [comment]
Løste det med å fjerne litt padding. Testet på iphone4

**Comment by raae** [comment]
Synes de fortsatt er litt store.

**Comment by raae** [comment]
![uploads/e59356e7-4622-4b80-9d0a-aeaee5b1ec78/IMG_8531-kopi.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe59356e7-4622-4b80-9d0a-aeaee5b1ec78%2FIMG_8531-kopi.jpg)

**Comment by kjellivar** [comment]
Gjort mindre

**Comment by raae** [comment]
:thumbsup:
