### ISSUE TITLE
Need new icons for landslide/flood couses

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#117]
Kan du sende meg ikonsettet jeg ser her @erjohnse ?

![uploads/3afa266e-8a18-44d2-986a-afdf929f9073/Hordaland_-_Flom-_og_jordskredvarsel.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3afa266e-8a18-44d2-986a-afdf929f9073%2FHordaland_-_Flom-_og_jordskredvarsel.png)

**Comment by erjohnse** [comment]
[cause_icons.zip](https://github.com/bGraphic/varsom-hybrid/files/689940/cause_icons.zip)

**Comment by raae** [comment]
Takk @erjohnse
