### ISSUE TITLE
Production ready avalanche dummy view

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#12]
Should look good and give information about the avalanche season starting December 1.

**Comment by kjellivar** [comment]
LAget en enkel en 
![uploads/15679fb6-9527-42ec-932e-79cac230442e/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F15679fb6-9527-42ec-932e-79cac230442e%2Fblob)

**Comment by raae** [comment]
Bra, men kan gjøres om til "Snøskredsdelen av appen er ikke klar enda".

**Comment by kjellivar** [comment]
done
