### ISSUE TITLE
Stuck in english varsom.no

### ISSUE THREAD

**Issue by erjohnse** [bGraphic/varsom-hybrid#125]
After using "Lenker til varsom.no" -> English, I'm stuck in varsom.no and can not go back to app without terminating Ionic View.

**Comment by erjohnse** [comment]
Missing back-function on all links to varsom.no

**Comment by raae** [comment]
Dette fungerer når den ikke er i ionic view

**Comment by raae** [comment]
Det fantes en fiks, nå i ionic view.
