### ISSUE TITLE
Avvalanche B-regions with active warning need to be more visible in list-view

### ISSUE THREAD

**Issue by erjohnse** [bGraphic/varsom-hybrid#126]
Any suggestions?

**Comment by raae** [comment]
Jeg tenker at er du interessert i området og legger den på favoritter dukker den opp under dine områder. Og så vil den også dukke opp på kartet om du er i nærheten. Men det er i mulig (i senere versjon) å lage en "aktive b-regioner"- og en "uaktive b-regioner" liste @erjohnse.

**Comment by raae** [comment]
Klarte ikke å motstå fristelsen, gikk så raskt (15 min).


![uploads/9b4e5c4f-0ba7-4aae-9508-d6deb21c5ee1/Varsom2_-_Ionic_Lab.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9b4e5c4f-0ba7-4aae-9508-d6deb21c5ee1%2FVarsom2_-_Ionic_Lab.png)

**Comment by erjohnse** [comment]
Sweet!
