### ISSUE TITLE
New app assets?

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#129]
Ny logo, splash screen @erjohnse?

**Comment by erjohnse** [comment]
[Icons varsom og regobs.zip](https://github.com/bGraphic/varsom-hybrid/files/698699/Icons.varsom.og.regobs.zip)

**Comment by erjohnse** [comment]
I zip-fila ligger logo for både iOS og ANdroid. Ignorer regobs-mappa :-)

**Comment by raae** [comment]
Created an illustrator file as to generate from, but seems shadow is removed when the icons are generated. Will try again.

**Comment by erjohnse** [comment]
[Icons varsom og regobs.zip](https://github.com/bGraphic/varsom-hybrid/files/699074/Icons.varsom.og.regobs.zip)

Hva med denne mappa? Kommer fra _MACOSX-mappe
