### ISSUE TITLE
Push-varsel - mangler detaljer om hva som varsles

### ISSUE THREAD

**Issue by erjohnse** [bGraphic/varsom-hybrid#147]
Fikk følgendemelding: AvalaancheWarnig forecast changed. Men hva forandret seg, og hvor?

**Comment by raae** [comment]
Det var fra det gamle systemet, ser ut som det nye ikke varsler på prod. Må undersøke nærmere hvorfor. Varslet fint på beta.

**Comment by raae** [comment]
Pushvarsler blir nå sendt.
