### ISSUE TITLE
Open map view with the tapped county selected

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#15]
When the user taps a county in the map it should be selected when the map is opened.

In addition: 
- [x] change the color in main view on tap, so the user can see that he/she tapped a county
- [x] open map zoomed in simlar to as in main view

**Comment by raae** [comment]
Work on together on monday.

**Comment by kjellivar** [comment]
substantially improved

**Comment by raae** [comment]
Dette må du prøve @erjohnse, kartet er blitt super nice! 
:thumbsup: @kjellivar
