### ISSUE TITLE
Tap on county in map displays county detailed view

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#2]
Tap on county displays detailed information for the county.

For this issue only show a simple view with name of county and some info.

**Comment by raae** [comment]
**Flomvarsel**
![uploads/eb362578-8a95-40dc-9259-208d19eb3949/iOS Simulator Screen Shot 22. okt. 2014 17.33.32.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feb362578-8a95-40dc-9259-208d19eb3949%2FiOS+Simulator+Screen+Shot+22.+okt.+2014+17.33.32.png)

**Jordskredvarsel**
![uploads/46abf08e-128c-466f-8d3c-3650b422a9ea/iOS Simulator Screen Shot 22. okt. 2014 17.33.52.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F46abf08e-128c-466f-8d3c-3650b422a9ea%2FiOS+Simulator+Screen+Shot+22.+okt.+2014+17.33.52.png)

**Comment by raae** [comment]
When tapping area on map it turns gray, should be a different shade of the original color.

**Comment by kjellivar** [comment]
Made fix
