### ISSUE TITLE
Back button in Settings "feels" funny

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#20]
The three menu options feels like seperate sections and should not know about each others state ...

**Comment by raae** [comment]
Remove it. To get back to "snøskred" or "Jordskred / flom" the user must use the hamburger.

**Comment by raae** [comment]
"snøskred" or "Jordskred / flom" must remember their state when jumping between them.

**Comment by raae** [comment]
Er det over vanskelig @kjellivar? Isåfall lager jeg en egen "lapp" på det og så fjerne vi back button når det er gjort.

**Comment by kjellivar** [comment]
Settings har ikke noen back button lengre nå, men at snøskred og jordskred husker staten sin er litt mer jobb. Lag gjerne en ny lapp på det

**Comment by raae** [comment]
Will do!
