### ISSUE TITLE
Create wireframes for avalanche region detailed view

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#21]

**Comment by kjellivar** [comment]
![uploads/883701bb-6580-417f-86cd-edcbff00ac67/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F883701bb-6580-417f-86cd-edcbff00ac67%2Fblob)
Avalanche og municipality detaljvisning. Foreslår å kun vise kortbeskrivelse på hver forecast, også vise avalanche problems, lang beskrivelse osv hvis man trykker på kortbeskrivelsen. Avalancheproblem kan evt. flyttes ut sammen med kortbeskrivelse hvis dette er noe som er viktig for majoriteten av brukerne,

**Comment by erjohnse** [comment]
Skredproblem dag 0 ( mandag i skissen) er viktigere enn hovedbudskap for
neste dag.

19. januar 2016 kl. 19.48 skrev Kjell Ivar Storstein <
notifications@github.com>:

**Comment by kjellivar** [comment]
@erjohnse Da skal jeg oppdatere skissen og ta inn det på fredag.

**Comment by kjellivar** [comment]
Her er den oppdaterte skissen. Ikke tenk på "snørosen" til høyre, den var et eksperiment bare.
![uploads/bd047cd7-6aa2-4968-a1fe-11d403f1bfc0/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbd047cd7-6aa2-4968-a1fe-11d403f1bfc0%2Fblob)
