### ISSUE TITLE
Avalanche Region view

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#22]
The same as county view with a map and a list.

The map default position when the user is not in an avalanche region to be decided in seperate issue, for now use same logic as with county view.

**Comment by kjellivar** [comment]
Issue #15 will also affect this one

**Comment by raae** [comment]
Cannot scroll. Bug?

**Comment by kjellivar** [comment]
Bug. Fixed now..

**Comment by raae** [comment]
:thumbsup:
