### ISSUE TITLE
When zooming in and out at some point weird things happen to the map

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#25]
![uploads/25606800-6ceb-4738-bb54-47c35e17dae3/IMG_8531.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F25606800-6ceb-4738-bb54-47c35e17dae3%2FIMG_8531.jpg)

**Comment by kjellivar** [comment]
Bug i leaflet og iOS9, prøvde å oppgradere leaflet, virker å ha hjulpet

**Comment by raae** [comment]
Fortsatt en del problemer her. Skal dobbelsjekke at jeg har rett versjon.

**Comment by raae** [comment]
Set ut som det fungere nå.

**Comment by raae** [comment]
Or not, se på det på mandag.

**Comment by raae** [comment]
Virker som det er bedre, så vi arkiverer denne for nå.
