### ISSUE TITLE
Create wireframe for municipality detailed view

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#3]
How should county detailed view look like when displaying flood and landslide (and later potentially avalanche)?

**Comment by raae** [comment]
**Flomvarsel** i OS-appen
![uploads/eb362578-8a95-40dc-9259-208d19eb3949/iOS Simulator Screen Shot 22. okt. 2014 17.33.32.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Feb362578-8a95-40dc-9259-208d19eb3949%2FiOS+Simulator+Screen+Shot+22.+okt.+2014+17.33.32.png)

**Jordskredvarsel** i OS-appen
![uploads/46abf08e-128c-466f-8d3c-3650b422a9ea/iOS Simulator Screen Shot 22. okt. 2014 17.33.52.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F46abf08e-128c-466f-8d3c-3650b422a9ea%2FiOS+Simulator+Screen+Shot+22.+okt.+2014+17.33.52.png)

**Comment by kjellivar** [comment]
![uploads/883701bb-6580-417f-86cd-edcbff00ac67/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F883701bb-6580-417f-86cd-edcbff00ac67%2Fblob)
Avalanche og municipality detaljvisning. Foreslår å kun vise kortbeskrivelse på hver forecast, også vise avalanche problems, lang beskrivelse osv hvis man trykker på kortbeskrivelsen. Avalancheproblem kan evt. flyttes ut sammen med kortbeskrivelse hvis dette er noe som er viktig for majoriteten av brukerne,

**Comment by erjohnse** [comment]
Skredproblem dag 0 ( mandag i skissen) er viktigere enn hovedbudskap for neste dag (tirsdag i skissen).

**Comment by raae** [comment]
Takk for innspill @erjohnse

**Comment by raae** [comment]
Ser @kjellivar svarte på den andre lappen.
