### ISSUE TITLE
Add labels to avalanche problems

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#45]
Add labels like on varsom.no

Part of #31

![uploads/dcd2443c-fc63-4861-ad49-5e11b0c5f75e/Screen_Shot_2016-02-19_at_13_47_53.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdcd2443c-fc63-4861-ad49-5e11b0c5f75e%2FScreen_Shot_2016-02-19_at_13_47_53.jpg)

**Comment by erjohnse** [comment]
Move height (and exposition) up above "Skredtype"

**Comment by raae** [comment]
Ta en titt @kjellivar

**Comment by kjellivar** [comment]
done
