### ISSUE TITLE
Small design issues

### ISSUE THREAD

**Issue by raae** [bGraphic/varsom-hybrid#51]
Se your own notes @kjellivar

**Comment by erjohnse** [comment]
Avalanche - Add <DangerLevelName> to Danger level on region page.

**Comment by erjohnse** [comment]
Change header colour in app from blue to grey. Will follow up on the colour code asap

**Comment by erjohnse** [comment]
Add NVE-logo on the bottom of the meny-selection.

**Comment by erjohnse** [comment]
Adjustments on asvalanche problem leaf. (see file)
![fil 09 03 2016 11 59 31](https://cloud.githubusercontent.com/assets/142221/13633470/85e7c1e6-e5ef-11e5-96bf-342c59fa7bb6.png)

**Comment by raae** [comment]
Takk for innspill @erjohnse, funker bra at du kommenterer her på GitHub!

**Comment by raae** [comment]
Kan du sende orginalversjon av NVE logo til oss, eller laste opp her @erjohnse?

**Comment by erjohnse** [comment]
EPS, PSD, Gid eller JPG?

2016-03-11 13:01 GMT+01:00 Benedicte Raae <notifications@github.com>:

**Comment by kjellivar** [comment]
PSD hadde vært aller best tror jeg

**Comment by erjohnse** [comment]
[NVELogoPos.zip](https://github.com/bGraphic/varsom-hybrid/files/169197/NVELogoPos.zip)

**Comment by kjellivar** [comment]
Takk:) Finnes logoen i andre farger? Invertert/sort-hvitt e.l.? Bare merker at den blir litt skjærende mot den bakgrunnsfargen som er nå.

**Comment by erjohnse** [comment]
Fikser i morgen

Den fredag 11. mars 2016 skrev Kjell Ivar Storstein <
notifications@github.com> følgende:

**Comment by erjohnse** [comment]
[NVELogoSort.zip](https://github.com/bGraphic/varsom-hybrid/files/171543/NVELogoSort.zip)

**Comment by kjellivar** [comment]
Supert takk @erjohnse , har lagt ut med endret logo

**Comment by raae** [comment]
Hva med hvitt? Den sklir nesten inn i det sorte.

**Comment by raae** [comment]
Samme versjon som på nve.no?

**Comment by erjohnse** [comment]
![nve-logo](https://cloud.githubusercontent.com/assets/142221/13778296/53a723aa-eab5-11e5-8985-fac12db35527.png)

**Comment by raae** [comment]
Fikser du logo @kjellivar .

**Comment by raae** [comment]
Kunne vi fått NVE logoen som er på skissene @erjohnse?


![uploads/63985b8c-7469-449d-a9ef-9842be0d2d73/_1__Varsom_no_redesign_2016_Preview_Mode_-_InVision.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F63985b8c-7469-449d-a9ef-9842be0d2d73%2F_1__Varsom_no_redesign_2016_Preview_Mode_-_InVision.jpg)

**Comment by erjohnse** [comment]
Sender den over på mandaqg. Nå drar jeg til Romsdalen, Vengetind venter på
meg

​

2016-04-19 16:03 GMT+02:00 Benedicte Raae <notifications@github.com>:

**Comment by erjohnse** [comment]
2016-04-20 12:14 GMT+02:00 Erik Rose Johnsen <erjohnse@gmail.com>:

**Comment by raae** [comment]
Logo issue flyttet til #73
