### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by erjohnse** [bGraphic/varsom-hybrid#57]
Add png's with "Vannføringsprognose" to flom/jordskred. (Add to map selector?)
Day 0: http://www2.nve.no/h/hd/prognosekart/progkart_1.png
Day 1: http://www2.nve.no/h/hd/prognosekart/progkart_2.png
Day 2: http://www2.nve.no/h/hd/prognosekart/progkart_3.png

**Comment by erjohnse** [comment]
Add observations from regobs to "snøskred". 
Sorted by region and date.

**Comment by raae** [comment]
Jeg splitter dem opp i egne lapper, lag gjerne en per ting så kan vi diskutere.
